# Amazing Web Services S3 bucket credentials
S3_BUCKET: ""
S3_ACCESS_KEY_ID: ""
S3_SECRET_ACCESS_KEY: ""

# Zencoder credentials for video encoding
ZENCODER_API_KEY: ""

# Sendgrid credentials for sending confirmation emails
SENDGRID_USERNAME: ""
SENDGRID_PASSWORD: ""
